django_linkbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^links/', include('libox.urls')),
]

libox/urls.py
from django.conf.urls import url
from . import views

app_name = 'libox'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # /links/552/
    # url(r'^(?P<card_id>[0-9]+)/$', views.detail, name='detail'),

    # register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # login
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),

    # logout
    url(r'^logout/$', views.logout_view, name='logout'),

    # LinkCard api
    url(r'^api/linkcard/$', views.LinkCardApi.as_view(), name='linkcard_api'),
]

libox/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class LinkCard(models.Model):
    link = models.CharField(max_length=1024)
    comment = models.CharField(max_length=1024)
    createdAt = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)
    isFavorite = models.BooleanField(default=False)

    def __str__(self):
        return self.comment[:25] + ' - ' + self.user.username

    def as_dict(self):
        return {
            'link'      : self.link,
            'comment'   : self.comment,
            'createdAt' : str(self.createdAt),
            'id'        : self.pk,
            'isFav'     : self.isFavorite
        }

    class Meta:
        ordering = ['createdAt']

libox/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

libox/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm
from .models import LinkCard
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse

from django.views.decorators.csrf import csrf_protect

from django.conf import settings

import json

# Create your views here.
def index(request):
    if request.user.is_authenticated():
        all_links = LinkCard.objects.filter(user=request.user).all()[::-1]
        context = {'all_links': all_links[:10]}
        return render(request, 'libox/index.html', context)
    else:
        return redirect('libox:login')

def detail(request, card_id):
    linkcard = get_object_or_404(LinkCard, id=card_id)
    
    return render(request, 'libox/detail.html', {'linkcard': linkcard})


class LinkCardApi(View):
    
    response = {}

    def get(self, request):
        if request.user.is_authenticated():
            offset = int( request.GET.get('offset', 0) )
            all_links = LinkCard.objects.filter(user=request.user).all()[::-1]
            dict_of_links = [link.as_dict() for link in all_links[offset : offset + 10]]
            self.response = {"list": dict_of_links, "total": len(all_links) }
        else:
            self.response = {"error":"No auth"}

        return HttpResponse(json.dumps(self.response), content_type="application/json")

    def post(self, request):
        if request.user.is_authenticated():
            try:
                # request.POST.get doesn't work with js fetch polyfill O_o
                json_data = json.loads( request.body.decode('utf8') )
                link    = json_data['link']
                comment = json_data['comment']
                user    = request.user.id

                card = LinkCard(link=link, comment=comment, user_id=user)
                card.save()

                self.response = {"success":True, "data":card.as_dict()}
            except:
                self.response = {"success":False, "error":"Unknown"}
        else:
            self.response = {"success":False, "error":"No auth"}
            return redirect('libox:login')

        return HttpResponse(json.dumps(self.response), content_type="application/json")

    def patch(self, request):
        if request.user.is_authenticated():
            try:
                json_data = json.loads( request.body.decode('utf8') )

                pk    = json_data['id']
                isFav = json_data['isFav']
                user  = request.user.id


                card = LinkCard.objects.filter(pk=pk, user_id=request.user.id)
                card.update(isFavorite=isFav)
                card = card.get()

                self.response = {"success":True, "data":card.as_dict()}
            except Exception as e:
                if settings.DEBUG:
                    self.response = {"success":False, "error":str(e)}
                else:
                    self.response = {"success":False, "error":"Unknown"}
        else:
            self.response = {"success":False, "error":"No auth"}
        return HttpResponse(json.dumps(self.response), content_type="application/json")

    def delete(self, request):
        if request.user.is_authenticated():
            try:
                # Parsing request's body as json
                json_data = json.loads( request.body.decode('utf8') )

                pk   = json_data['id']
                user = request.user.id

                card = LinkCard.objects.get(pk=pk, user_id=request.user.id)
                card.delete()

                self.response = {"success":True}
            except:
                self.response = {"success":False, "error":"No such card"}
        else:
            self.response = {"success":False, "error":"No auth"}

        return HttpResponse(json.dumps(self.response), content_type="application/json")



class UserFormView(View):
    form_class = UserForm
    template_name = 'libox/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('libox:index')

        return render(request, self.template_name, {'form':form})



class UserLoginView(View):
    form = ['username','password']
    template_name = 'libox/login.html'

    def get(self, request):
        return render(request, self.template_name, {"form":self.form,'error':''})
        
    def post(self, request):

        # cleaned (normalized) data
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")


        # returns User objects if credentials are correct
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('libox:index')

        return render(request, self.template_name, {'form':self.form,'error':'There was an error.'})

def my_view(request):
    username = request.POST.get('username','')
    password = request.POST.get('password','')
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('libox:index')
    return render(request, 'libox/login.html')

def logout_view(request):
    logout(request)
    return redirect('libox:login')

libox/templates/libox/base.html
<html>
    <head>
        {% load staticfiles %}
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'libox/css/custom.css' %}">
    </head>
    <body>
        {% block main %}
        {% endblock %}
    </body>
</html>

libox/templates/libox/detail.html
<h3>This is detail view for card #{{ linkcard.id }}</h3>
<p>{{ linkcard.comment }}</p>

libox/templates/libox/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <div class="col-md-10">
            <label class="control-label col-md-2">{{ field.label_tag }}</label>
            {{ field }}
        </div>
    </div>
{% endfor %}

libox/templates/libox/index.html
{% extends 'libox/base.html' %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            
            <!-- Statistics -->
            
            <div class="row stats">
                <div class="col-xs-2"><a href="logout/">{{ request.user.username }}</a></div>
                <div class="col-xs-2"></div>
                <div class="col-xs-2">3</div>
                <div class="col-xs-2">4</div>
                <div class="col-xs-2">5</div>
                <div class="col-xs-2">6</div>
            </div>
        </div>
    </div>

    <div id="cardContainer"></div>

</div>

{% load staticfiles %}
<script src="{% static 'libox/src/bundle.js' %}"></script>
{% endblock %}

libox/templates/libox/login.html
{% extends 'libox/base.html' %}

{% block main %}
<div class="col-md-2 col-md-offset-5">
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <span class="text-danger small">{{ error }}</span>
            </div>
            <div class="col-md-10">
                <label class="control-label col-md-2">{{ form.0 }}</label>
                <input name="{{ form.0 }}" type="text">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2">{{ form.1 }}</label>
                <input name="{{ form.1 }}" type="password">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <div class="login-form-buttons">
                    <button type="submit">Login</button>
                    <a href="{% url 'libox:register' %}">Register</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

libox/templates/libox/registration_form.html
{% extends 'libox/base.html' %}

{% block main %}
<div class="col-md-2 col-md-offset-5">
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        {% include 'libox/form-template.html' %}
        <div class="form-group">
            <div class="col-md-12">
                <div class="login-form-buttons">
                    <button type="submit">Register</button>
                    <a href="{% url 'libox:login' %}">Login</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}